### PR TITLE
enable GitHub Workflow

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by mohawk2** [comment]
Thanks for this. Could you base it on https://github.com/graphviz-perl/GraphViz2/blob/master/.github/workflows/linux.yml but make it go back to 5.6 if possible? Also, I see no reason for a scheduled run.

**Comment by szabgab** [comment]
I am experimenting with the idea of the scheduled run to catch failures caused by changing dependencies even while you are not making changes to your code.

**Comment by szabgab** [comment]
Sent a new PR: #15

**Comment by mohawk2** [comment]
Thanks - please experiment in your own code first :-) Also, it causes less traffic to simply force-push a branch rather than close and reopen.

**Comment by szabgab** [comment]
I mistakenly removed the remote branch and that closed the PR automatically.

I know for me the scheduled CI runs are useful, I just don't know how others will like it.

**Pull request closed without merging**
